### ISSUE TITLE
"NoSuchMethodError" during startup  using Secrets Manager config

### ISSUE THREAD

**Issue by mikelhamer** [awspring/spring-cloud-aws#738] opened 2023-03-25 22:40 UTC
**Type**: Bug

**Component**:
Secrets Manager

**Describe the bug**
I get a "NoSuchMethodError" when initializing my application using Secrets Manager config

> 2023-03-25 21:37:04.768 WARN 1 --- [ main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'secretsManagerPollingAwsPropertySourceChangeDetector' defined in class path resource [io/awspring/cloud/autoconfigure/config/secretsmanager/SecretsManagerReloadAutoConfiguration.class]: Invocation of init method failed; nested exception is java.lang.NoSuchMethodError: 'void org.springframework.scheduling.support.PeriodicTrigger.<init>(java.time.Duration)'

`pom.xml`
``` xml

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.0.5</version>
        <relativePath/>
    </parent>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.awspring.cloud</groupId>
                <artifactId>spring-cloud-aws-dependencies</artifactId>
                <version>3.0.0-RC1</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <!-- Spring Cloud AWS -->
        <dependency>
            <groupId>io.awspring.cloud</groupId>
            <artifactId>spring-cloud-aws-autoconfigure</artifactId>
        </dependency>
        <dependency>
            <groupId>io.awspring.cloud</groupId>
            <artifactId>spring-cloud-aws-starter-secrets-manager</artifactId>
        </dependency>
        <dependency>
            <groupId>io.awspring.cloud</groupId>
            <artifactId>spring-cloud-aws-starter-sns</artifactId>
        </dependency>
        <dependency>
            <groupId>io.awspring.cloud</groupId>
            <artifactId>spring-cloud-aws-starter-s3</artifactId>
        </dependency>
    </dependencies>
```

application.properties

``` properties
# Import configuration from Secrets Manager
spring.config.import=aws-secretsmanager:/secret/myapp
# Add refresh scope reload capability for secrets properties
spring.cloud.aws.secretsmanager.reload.strategy=refresh

```

**Comment by maciejwalkowiak** [comment] 2023-03-25 23:36
Looks like a bug. @mikelhamer would you like to contribute a fix?

**Comment by maciejwalkowiak** [comment] 2023-03-25 23:36
Looks like a bug. @mikelhamer would you like to contribute a fix?

**Comment by mikelhamer** [comment] 2023-03-25 23:45
> Looks like a bug. @mikelhamer would you like to contribute a fix?

 I've never contributed to anything like this before but I would love to. Outside of checking in `SecretsManagerReloadAutoConfiguration` and `PeriodicTrigger`, do you have any advice on where I should start or things I should know? In this case if it's trying to call a method that doesn't exist, I assume I would need to replace it witch a similar functionality with some method that does exist.

**Comment by maciejwalkowiak** [comment] 2023-03-26 00:04
This exception means that the version of PeriodicTrigger on your class path is different than one we use during Spring Cloud AWS compilation. The question is why? And i can't tell without looking through the code which won't happen this weekend

**Comment by mikelhamer** [comment] 2023-03-26 00:15
Got it, I'll see what I can find!

**Comment by mikelhamer** [comment] 2023-03-26 13:50
@maciejwalkowiak I'm not sure if this is a bug or something with my deployment. I cannot for the life of me recreate this locally, but it happens on startup in ECS on AWS. I'm using a local properties file locally but when I deploy to ECS it's using the `spring.config.import=aws-secretsmanager:/secret/myapp` import. I thought this alone was the culprit so I switched my local environment to do the same, but alas, everything starts up fine. As far as I can tell everywhere in my app is using Spring Framework 6.0.7, and it seems Spring Cloud AWS 3.0.0-RC2 is using 6.0.4 so there is only a small difference there and the `PeriodicTrigger(Duration)` constructor exists in both of them. Really stumped at where to even look next, but it appears my problem may be beyond the scope of this project. If you can't recreate either then we can probably just close this. Thanks for pointing me in the right direction and giving me ideas though :)

**Comment by maciejwalkowiak** [comment] 2023-03-26 13:54
@mikelhamer would you be able to attach a sample project that reproduces this issue? Or maybe also a full exception stacktrace. If it happened to you, it may happen to others so I'll try to figure it out.

**Comment by mikelhamer** [comment] 2023-03-26 14:04
@maciejwalkowiak ok I don't know how I missed this (probably from only looking at limited logs view in ECS vs CloudWatch), but hunting down the full stack trace has revealed there is in fact a conflict that it is trying to using Spring Framework 5.x


```
***************************
APPLICATION FAILED TO START
***************************
Description:
An attempt was made to call a method that does not exist. The attempt was made from the following location:
io.awspring.cloud.autoconfigure.config.reload.PollingAwsPropertySourceChangeDetector.afterPropertiesSet(PollingAwsPropertySourceChangeDetector.java:54)
The following method did not exist:
'void org.springframework.scheduling.support.PeriodicTrigger.<init>(java.time.Duration)'
The calling method's class, io.awspring.cloud.autoconfigure.config.reload.PollingAwsPropertySourceChangeDetector, was loaded from the following location:
jar:file:/app/BOOT-INF/lib/spring-cloud-aws-autoconfigure-3.0.0-RC1.jar!/io/awspring/cloud/autoconfigure/config/reload/PollingAwsPropertySourceChangeDetector.class
The called method's class, org.springframework.scheduling.support.PeriodicTrigger, is available from the following locations:
jar:file:/app/BOOT-INF/lib/spring-context-5.3.24.jar!/org/springframework/scheduling/support/PeriodicTrigger.class
The called method's class hierarchy was loaded from the following locations:
org.springframework.scheduling.support.PeriodicTrigger: file:/app/BOOT-INF/lib/spring-context-5.3.24.jar
Action:
Correct the classpath of your application so that it contains compatible versions of the classes io.awspring.cloud.autoconfigure.config.reload.PollingAwsPropertySourceChangeDetector and org.springframework.scheduling.support.PeriodicTrigger
```

**Comment by maciejwalkowiak** [comment] 2023-03-26 14:36
Yes! Which would mean that perhaps you're using Spring Boot 2.x?

**Comment by mikelhamer** [comment] 2023-03-26 14:49
I recently updated to use Spring Boot 3.0.5. My current guess is that maybe it's caching 2.7.6 (my previous version) behind the scenes somewhere

**Comment by maciejwalkowiak** [comment] 2023-03-26 15:12
Understood. I'll close it then. If anything new pops up please drop a comment and I'll reopen.

**Closed by maciejwalkowiak** 2023-03-26 15:12 UTC
Labels: type: bug, component: secrets-manager

**Comment by mikelhamer** [comment] 2023-03-26 18:47
Confirmed this was a Docker layer caching issue in ECS / ECR. Thank you so much for your suggestions and support!
