### ISSUE TITLE
Spring Boot 3.2.2 @SqsListener Not listening to the Queue

### ISSUE THREAD

**Issue by WoodenCode00** [awspring/spring-cloud-aws#1028] opened 2024-01-23 16:23 UTC
**Type**: Bug

**Component**: SQS

**Describe the bug**
After  upgrading from Spring Boot 2.7.18 to 3.2.2 the `@SqsListener` annotation doesn't listen to the SQS queue. I made some experimentations, for example, I added `@PostConstruct` method to the class with a simple logger, and I can see that the log doesn't get printed. Interesting that after adding a `@Scheduled(fixedRate = 5000)` on the method in this class, all of a sudden the log message from PostConstruct comes out and SqsListener method starts to consume the messages.

Another fact, the below log statement is not printed, though I can see it after adding `@Scheduled` method:
 `2024-01-19 17:40:48.546   [lifecycle-thread-1] INFO  io.awspring.cloud.sqs.listener.AbstractMessageListenerContainer.start - Container io.awspring.cloud.sqs.sqsListenerEndpointContainer#0 started
`

**Sample**
```
@Slf4j
@Component
@RequiredArgsConstructor
@FieldDefaults(level = AccessLevel.PRIVATE, makeFinal = true)
public class MySqsConsumer  {

  @PostConstruct
  public void init() {
    var bean = applicationContext.getBean(SqsListenerAnnotationBeanPostProcessor.class);
    log.info("Loaded SqsListenerAnnotationBeanPostProcessor: {}", bean);
  }

  @SqsListener("https://sqs.us-east-1.amazonaws.com/account-id/my-queue")
   public void consume(String message) {
     log.info("Message: {}", message);
  }
}
```

UPDATE: versions used:
```
 <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.2.2</version>
        <relativePath/>
    </parent>

          <dependency>
                <groupId>io.awspring.cloud</groupId>
                <artifactId>spring-cloud-aws-dependencies</artifactId>
                <version>3.1.0</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
```

UPDATE: output of bean resolutions - all looks normal, though the queue is not getting polled:

```
 ============================
 CONDITIONS EVALUATION REPORT
 ============================


   SqsAutoConfiguration matched:
      - @ConditionalOnClass found required classes 'software.amazon.awssdk.services.sqs.SqsAsyncClient', 'io.awspring.cloud.sqs.config.SqsBootstrapConfiguration' (OnClassCondition)
      - @ConditionalOnProperty (spring.cloud.aws.sqs.enabled=true) matched (OnPropertyCondition)

   SqsAutoConfiguration#defaultSqsListenerContainerFactory matched:
      - @ConditionalOnMissingBean (types: io.awspring.cloud.sqs.config.SqsMessageListenerContainerFactory; SearchStrategy: all) did not find any beans (OnBeanCondition)

   SqsAutoConfiguration#sqsAsyncClient matched:
      - @ConditionalOnMissingBean (types: software.amazon.awssdk.services.sqs.SqsAsyncClient; SearchStrategy: all) did not find any beans (OnBeanCondition)

   SqsAutoConfiguration#sqsTemplate matched:
      - @ConditionalOnMissingBean (types: io.awspring.cloud.sqs.operations.SqsTemplate; SearchStrategy: all) did not find any beans (OnBeanCondition)
```

**Comment by tomazfernandes** [comment] 2024-01-28 02:56
Hi @WoodenCode00, would you be able to create and share a sample application that reproduces the issue without the @PostConstruct annotation?

Thanks.

**Comment by WoodenCode00** [comment] 2024-01-29 18:54
Let me see... Interesting that in the new clean project the `@SqsListener`  works.
Trying to reproduce the problem in the new project...

**Comment by WoodenCode00** [comment] 2024-01-31 15:58
I couldn't reproduce the issue in a new project. As a workaround, I refactored the code to create a bean of `MessageListenerContainer` in `@Configuration` class. This way the container is able to listen to the queue.

**Comment by tomazfernandes** [comment] 2024-02-07 23:05
@WoodenCode00 since it seems you solved your problem, I'll close this issue.

We can reopen it if you'd like and feel free to provide more details on your configuration if you want to investigate this further.

Thanks.

**Closed by tomazfernandes** 2024-02-07 23:05 UTC
Labels: component: sqs, status: waiting-for-feedback

**Comment by fsamir** [comment] 2024-11-20 08:20
I had the same issue and found the root cause here: https://stackoverflow.com/questions/75181017/aws-sqslistener-not-working-with-spring-cloud-using-springboot-3

In short, use io.awspring.cloud.sqs.annotation.SqsListener to listen the messages instead of io.awspring.cloud.messaging.listener.annotation.SqsListener.
