### ISSUE TITLE
Messages not consumed from SQS queue

### ISSUE THREAD

**Issue by vijayrcse** [awspring/spring-cloud-aws#270] opened 2022-03-19 13:00 UTC
**Type**: Bug

**Component**:
SQS

**Describe the bug**
I have @SqsListener configured in one of the method  of my spring @Service class. I am using version of spring-cloud-aws-messaging 2.2.6.RELEASE
At times ( very rarely ) I see that messages in the queue is not getting consumed. The listener method is not even invoked.

I had to bounce our spring boot container process to fix the issue. There is nothing in the logs with respect to errors. As of now using only the default configuration and not customized task executor or SimpleMessageListenerContainer bean.
Unable to reproduce the issue in test environments.
Could you please suggest what could be wrong here and how I can troubleshoot this issue ?

**Sample**
@SqlListener(value="${queue.name}", deletionPolicy=SqsMessageDeletionPolicy.ON_SUCCESS) {
  ...
}

**Comment by LarcomLabs** [comment] 2022-08-14 01:51
I have this same issue. First time using this library though, so I have no idea if its a config issue or an actual bug. Nobody has replied to anything ive posted

**Comment by manjian14** [comment] 2022-08-18 06:54
Also, I have the same issue too

**Comment by vijayrcse** [comment] 2022-08-18 06:59
I still have this issue. We are bouncing the container process when we come across this issue. Any inputs would help.

**Comment by maciejwalkowiak** [comment] 2022-08-21 06:15
@manjian14 @vijayrcse do you use the latest 2.4.2 version? There were many fixes in SQS integration since 2.2.6. Also, I am not able to reproduce this issue so if you could send a sample project with instructions how to reproduce it would be great.

**Comment by vijayrcse** [comment] 2022-08-21 12:51
I use 2.2.6.RELEASE. I tried to reproduce this issue in lower environment, but we couldn't. We could upgrade to 2.4,2 and see if this issue exist

**Comment by maciejwalkowiak** [comment] 2022-08-21 19:54
Sounds good to me!

**Comment by manjian14** [comment] 2022-08-22 06:30
2.2.6.RELEASE working fine, when I upgraded to the latest version '2.4.2' sending a message within SQS is working but is not getting consumed. The listener method is not invoked, my code changes between the old and latest version is the change the used package, and removes the SQS enable annotations because that was deprecated

**Comment by maciejwalkowiak** [comment] 2022-08-22 07:29
@manjian14 can you share a sample that reproduces it? We have a sample how to use SQS https://github.com/awspring/spring-cloud-aws/tree/2.4.x/spring-cloud-aws-samples/spring-cloud-aws-sqs-sample

**Comment by manjian14** [comment] 2022-08-22 08:03
Thank you, I tried your sample, and in the fact, my Implementation is very simple, just send and receive a message within SQS, only the changes which I have done after moving from 2.2.6.RELEASE to  2.4.2  is to create SQS Bean because SQSEnable was deprecated, and my SQS Bean is also simple, I don't use any credentials at the code level, because my project gets access to sqs by  aws roles,
my spring-boot version is 2.7.3 / Java 11

**Comment by maciejwalkowiak** [comment] 2022-08-23 04:44
@manjian14 did it work after upgrade? If not, maybe there is a permission problem or the queue does not exist? I'd need more details to figure the root cause.

**Comment by manjian14** [comment] 2022-08-23 06:02
after upgrade, sending a message via sqs is working, but not consumed to the listener, I don't think it's related to AWS permission because the older version working fine and with the latest version I am able to send a message

**Comment by manjian14** [comment] 2022-08-23 06:26
the only major change is I replaced this he EnableSqs annotation with  my own bean 

   @Bean
    public AmazonSQSAsync amazonSQSAsync(){
        return AmazonSQSAsyncClientBuilder.standard().withRegion(Regions.US_EAST_1).build();

    }

**Comment by maciejwalkowiak** [comment] 2022-08-23 10:12
Unfortunately I cannot reproduce it. Please create a repository with minimal example that reproduces this issue.

**Comment by manjian14** [comment] 2022-08-23 14:48
I figure out something  if I added @EnableSqs  " which is deprecated"  the latest lib 2.4.2 start work, otherwise, if I remove the EnableSqs , the code not consuming to the listener

**Comment by maciejwalkowiak** [comment] 2022-08-24 04:05
Then it means that for some reason the autoconfiguration is not triggered. Run application with debug mode (`debug=true` in `application.properties` and look for `SqsAutoConfiguration`).

**Comment by manjian14** [comment] 2022-08-24 07:00
Thank you, the issue has been fixed, the problem was related to autoconfiguration dependency

**Comment by maciejwalkowiak** [comment] 2022-08-24 10:22
Awesome! 

@vijayrcse are you guys working together or do you have a separate issue? If so, can you also verify that it is not an autoconfiguration problem?

**Comment by manjian14** [comment] 2022-08-24 10:37
nop, this is a separate issue, but I believe is the same reason

**Comment by vijayrcse** [comment] 2022-08-25 04:26
Issue raised by @manjian14 is a separate issue. Original issue reported by me on 2.2.6 still remains. We are looking at upgrading to 2.4.2 sooner

**Comment by tomazfernandes** [comment] 2023-03-14 23:19
Hey @maciejwalkowiak, maybe we can close this one in hopes that it won't happen in 3.0? Even if the problem did appear, I don't think info from this thread would be helpful. WDYT?

**Closed** 2023-04-20 04:05 UTC
Labels: type: bug, component: sqs, status: ideal-for-contribution
