### ISSUE TITLE
@SqsListener not working after upgrading to Spring Boot 3.1.3

### ISSUE THREAD

**Issue by julpalma** [awspring/spring-cloud-aws#914] opened 2023-10-19 15:15 UTC
**Type**: Bug

**Component**:
 SQS

**Describe the bug**
Please provide details of the problem, including the version of Spring Cloud that you
are using. 

After upgrading to Spring Boot 3.1.3, @SqsListener is not working anymore. My service is able to send a message to SQS queue but is not receiving the message. I have been trying to fix for more than 3 weeks now, but cant seem to figure this out.
Can someone please help me figure out what is missing?? Thank you!!!!

Note that the code below is for local testing. With Spring Boot 2.x it works fine.

This is my Configuration code, in the Configuration class:

```
@Bean
    public SqsAsyncClient sqsAsyncClient(){
        return SqsAsyncClient.builder().endpointOverride(URI.create("http://localhost:9324"))
                .region(Region.US_EAST_1)
                .credentialsProvider(StaticCredentialsProvider.create(new AwsCredentials() {
                    @Override
                    public String accessKeyId() {
                        return "Local";
                    }

                    @Override
                    public String secretAccessKey() {
                        return "local";
                    }
                }))
                .build();
    }

    @Bean
    public SqsTemplate sqsTemplateManualContainerInstantiation(SqsAsyncClient sqsAsyncClient) {
        return SqsTemplate.builder()
                .sqsAsyncClient(sqsAsyncClient)
                .build();
    }

    @Bean
    SqsMessageListenerContainerFactory defaultSqsListenerContainerFactory(SqsAsyncClient sqsAsyncClient) {
        return SqsMessageListenerContainerFactory
                .builder()
                .configure(options -> options
                        .pollTimeout(Duration.ofSeconds(10)))
                .sqsAsyncClient(sqsAsyncClient)
                .messageListener((message) -> log.info("Received SQS message {}", message))
                .build();
    }
```

This is the sendMessage code in the Service class.

```
public void sendMessage(Request request, User user) {
        try {
            MyServiceRequest payload = new MyServiceRequest(user, request.getEvent(), TrackingUtil.getTrackingId(), Instant.now().getEpochSecond());
            sqsTemplate.send("queueUrl", buildMessageRequest(payload));
        } catch (Exception e) {
            log.error("Failed to send message to SQS for user {}, cause by {}", user, e.getMessage());
        }
    }

private SendMessageRequest buildMessageRequest(MyServiceRequest payload) {
        MessageAttributeValue contentTypeJson = new MessageAttributeValue()
                .withDataType("String")
                .withStringValue("application/json");
        return new SendMessageRequest("queueUrl", toSqsFormat(payload))
                .addMessageAttributesEntry("contentType", contentTypeJson);
    }

    private String toSqsFormat(MyServiceRequest payload) {
        try {
            return objectMapper.writeValueAsString(payload);
        } catch (IOException e) {
            throw new IllegalArgumentException("Failed to convert payload " + message + " to JSON", e);
        }
    }
```

This is the listener code:
```
@SqsListener(value = "queueUrl", deletionPolicy = SqsMessageDeletionPolicy.ON_SUCCESS)
    public void onMessageReceived(MyServiceRequest message) {
        log.info("Received message from SQS");
    }
```

These are the AWS dependencies in the pom file:

       <dependency>
            <groupId>io.awspring.cloud</groupId>
            <artifactId>spring-cloud-aws-messaging</artifactId>
            <version>2.4.4</version>
        </dependency>

       <dependency>
            <groupId>io.awspring.cloud</groupId>
            <artifactId>spring-cloud-aws-starter-sqs</artifactId>
            <version>3.0.2</version>
        </dependency>

When i run the application with debug mode, i see this:

   SqsAutoConfiguration matched:
      - @ConditionalOnClass found required classes 'software.amazon.awssdk.services.sqs.SqsAsyncClient', 'io.awspring.cloud.sqs.config.SqsBootstrapConfiguration' (OnClassCondition)
      - @ConditionalOnProperty (spring.cloud.aws.sqs.enabled=true) matched (OnPropertyCondition)

   SqsAutoConfiguration#defaultSqsListenerContainerFactory:
      Did not match:
         - @ConditionalOnMissingBean (types: io.awspring.cloud.sqs.config.SqsMessageListenerContainerFactory; SearchStrategy: all) found beans of type 'io.awspring.cloud.sqs.config.SqsMessageListenerContainerFactory' defaultSqsListenerContainerFactory (OnBeanCondition)

   SqsAutoConfiguration#sqsAsyncClient:
      Did not match:
         - @ConditionalOnMissingBean (types: software.amazon.awssdk.services.sqs.SqsAsyncClient; SearchStrategy: all) found beans of type 'software.amazon.awssdk.services.sqs.SqsAsyncClient' sqsAsyncClient (OnBeanCondition)

   SqsAutoConfiguration#sqsTemplate:
      Did not match:
         - @ConditionalOnMissingBean (types: io.awspring.cloud.sqs.operations.SqsTemplate; SearchStrategy: all) found beans of type 'io.awspring.cloud.sqs.operations.SqsTemplate' sqsTemplateManualContainerInstantiation (OnBeanCondition)

In addition to that, when i check the QueueUrl, i see this:

![Screenshot 2023-10-19 at 12 25 27 PM](https://github.com/awspring/spring-cloud-aws/assets/148469611/e8ee1944-0080-48a7-8d3f-85108d1e8a07)

**Sample**
If possible, please provide a test case or sample application that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it.

**Comment by maciejwalkowiak** [comment] 2023-10-23 12:50
You're mixing Spring Cloud AWS 2.x with 3.x. If you're using Spring Boot 3, you must use Spring Cloud AWS 3.x. I am using SQS integration with Spring Boot 3.1.4 so definitely unless there is some unusual config, it does work as expected. 

Please try adjusting dependencies and let us know if it helped.

**Comment by maciejwalkowiak** [comment] 2023-10-24 14:04
I find it difficult to go through your code samples, formatting could be one of the reasons. Also, `com.amazonaws.event.ProgressListener` comes from AWS SDK v1.

Are you able to publish a complete project that reproduces your issue? Something I can checkout and run myself?

**Comment by julpalma** [comment] 2023-10-24 20:05
Thank you for the reply @maciejwalkowiak 

I had this dependency on my pom file:
                <groupId>com.amazonaws</groupId>
                <artifactId>aws-java-sdk-bom</artifactId>
                <version>1.12.395</version>
               <type>pom</type>
                <scope>import</scope>

I removed and added:
                <groupId>software.amazon.awssdk</groupId>
                <artifactId>bom</artifactId>
                <version>2.20.63</version>
                <type>pom</type>
                <scope>import</scope>

I see that the Listener container has started successfully:
I see this in the logs:
"Container io.awsspring.cloud.sqs.sqsListenerEndpointContainer#0 started"

I see the message is sent successfully as well.

However, i still see an error on the convert step:

java.lang.IllegalArgumentException: No class found with name com.amazonaws.services.sqs.model.SendMessageRequest
	at io.awspring.cloud.sqs.support.converter.AbstractMessagingMessageConverter.defaultHeaderTypeMapping(AbstractMessagingMessageConverter.java:197)
	at io.awspring.cloud.sqs.support.converter.AbstractMessagingMessageConverter.getTargetType(AbstractMessagingMessageConverter.java:179)
	at io.awspring.cloud.sqs.support.converter.AbstractMessagingMessageConverter.convertPayload(AbstractMessagingMessageConverter.java:170)

Not sure why it is looking for SendMessageRequest from the old path (SDK 1.X).

I have downloaded the jar from the new path: amazon.awssdk.services.sqs.model.SendMessageRequest

**Comment by julpalma** [comment] 2023-10-24 20:27
I also see this in the logs:

The Canonical String for this request should have been
'POST
/

amz-sdk-invocation-id:a09aa7d9-8de0-3407-9ba2-f0afb6406806
amz-sdk-request:attempt=1; max=4
content-length:36
content-type:application/x-www-form-urlencoded; charset=utf-8
host:sqs.us-east-1.amazonaws.com
x-amz-date:20231024T202249Z

amz-sdk-invocation-id;amz-sdk-request;content-length;content-type;host;x-amz-date
48a38266faf90970d6c7fea9b15e6ba366e5f6397c2970fc893f8a7b5e207bd0'

The String-to-Sign should have been
'AWS4-HMAC-SHA256
20231024T202249Z
20231024/us-east-1/sqs/aws4_request
f16de8f4962de2a48ec28b684c98ead52f1dbc6bcafe603317cb7329d5f0a3c8'
 (Service: Sqs, Status Code: 403, Request ID: 7f95ba3a-a036-56c0-83bf-e78889ec233f)

**Comment by julpalma** [comment] 2023-10-25 20:06
And i see this error:

The Canonical String for this request should have been
'POST
/

amz-sdk-invocation-id:5c407020-847c-c2a7-c4bc-86917bfee56e
amz-sdk-request:attempt=1; max=4
content-length:194
content-type:application/x-www-form-urlencoded; charset=utf-8
host:sqs.us-east-1.amazonaws.com
x-amz-date:20231025T181352Z

amz-sdk-invocation-id;amz-sdk-request;content-length;content-type;host;x-amz-date
522127270de60df776f808abc2797e1c1edb0b79baff2350e4b6f62651c3e3d8'

The String-to-Sign should have been
'AWS4-HMAC-SHA256
20231025T181352Z
20231025/us-east-1/sqs/aws4_request
c867198790efaa4356d16af8d2bae63bf886f61f84c726d5f94ab42c4ff80b82'
 (Service: Sqs, Status Code: 403, Request ID: c25fc9d1-af12-55e0-95db-9462f232a84e)
	at software.amazon.awssdk.services.sqs.model.SqsException$BuilderImpl.build(SqsException.java:104)

**Comment by julpalma** [comment] 2023-10-26 14:55
@maciejwalkowiak we found the issue.

The host was set to the real server, when we overwrite, it works fine. Thank you for your help. You can close this issue.

**Comment by maciejwalkowiak** [comment] 2023-10-26 15:19
Uff super happy you found it! I am closing it then!

**Closed by maciejwalkowiak** 2023-10-26 15:19 UTC
Labels: component: sqs, status: waiting-for-feedback

**Comment by tmdgusya** [comment] 2024-03-06 05:21
@maciejwalkowiak Thank you for kindness answering for us. Do you happen to have any documents for migrating 2.X to 3.X version related to `aws-messaging`? because I want to know what classes that I should use when migrate current class to higher version (migrated) classes.
