### ISSUE TITLE
Autoconfiguring AsyncSnsClient for SnsTemplate

### ISSUE THREAD

**Issue by firatsivrikaya** [awspring/spring-cloud-aws#998] opened 2023-12-14 10:51 UTC
**Type**: Feature

**Is your feature request related to a problem? Please describe.**
Hi,
SnsTemplate configures SnsClient as default, Is it possible to autoconfigure AsyncSnsClient for SnsTemplate.
Thank you very much.

**Describe the solution you'd like**
I would like to configure SnsTemplate to use AsyncSnsClient with a parameter or configuration.

**Additional context**
Spring Boot Version : 3.1.6
io.awspring.cloud:spring-cloud-aws-dependencies:3.0.4
'io.awspring.cloud:spring-cloud-aws-starter
io.awspring.cloud:spring-cloud-aws-starter-sns

**Comment by elkhart** [comment] 2024-07-01 12:27
Is this a duplicate of https://github.com/awspring/spring-cloud-aws/issues/687 ?

**Comment by maciejwalkowiak** [comment] 2024-09-19 13:41
Duplicate of #687.

**Closed by maciejwalkowiak** 2024-09-19 13:41 UTC
