### ISSUE TITLE
ParameterStore no more automatic resolution of locations

### ISSUE THREAD

**Issue by kerkhofsd** [awspring/spring-cloud-aws#569] opened 2022-12-08 12:24 UTC
**Type**: Bug / Question

**Component**:
Parameter Store

**Describe the bug**
We notice there's a difference in behaviour for loading configuration from the ParameterStore when upgrading to 3.0.0-M3. 

Given following configuration:
```
spring:
  application:
    name: foobar
  config:
    import: "optional:aws-parameterstore:"
```

In version 2.4.x this would load parameters from following locations: `/config/application/`, `/config/application_dev`, `/config/phy-foobar/` , `config/foobar_dev/`
(Assuming the `dev` profile is active and using the default values for `aws.paramstore.prefix`, `aws.paramstore.defaultContext`, `aws.paramstore.profileSeparator` and `aws.paramstore.name`)
 
However in version 3.0.0-M3, there is no more automatic resolution of these locations and locations should be explicitly listed. (E.g. `"aws-parameterstore:/config/application/;/config/application_dev/;/config/foobar/;/config/foobar_dev/"`

I'm creating this issue to get some insight in these changes.

* What is the rationale behind this change? (Is this by intention or rather an unfortunate side effect of changes made?)
* Following the above: is this a feature that might be re-introduced in 3.x ?
* Other than explicitly listing all the paths in the `spring.config.import` property value, is it somehow possible to reproduce the old behaviour? (I've been looking into the classes, but at this point I don't have a clue on how to extend / integrate with e.g. the `ParameterStorePropertySources`)

Thanks in advance for your feedback!

**Comment by MatejNedic** [comment] 2022-12-31 12:35
Hey @kerkhofsd , we have removed resolving by application name since it is not cost and perfromance effective. I suggest you rather specify which parameters you need by location. This is also a more cleaner and a better way to manage parameters since you load only what you need.

I don't think this should be re-introduced in 3.x since making calls to AWS that are not really needed only slows your startup and increses cost.

@maciejwalkowiak your input is welcome here

**Comment by maciejwalkowiak** [comment] 2023-01-01 20:55
As far as I can tell the old behavior can be reproduced exactly by manually specifying all the keys. I understand that this means more hassle for existing projects but considering the great number of issues we received related to this automatic resolution - I think it is more predictable and less "magic" for new projects.

If there is something that I missed and you are not able to list all the keys manually - please let us know.

At this stage we don't plan to re-introduce it in 3.0.

**Comment by kerkhofsd** [comment] 2023-01-02 12:31
Thanks for the feedback @MatejNedic and @maciejwalkowiak !

We understand that this won't be reintroduced and will work around the change by listing the explicit parameter locations.

**Comment by maciejwalkowiak** [comment] 2023-01-02 15:45
thanks @kerkhofsd for quick answer. lets keep the issue open for now and see if others come with similar feedback.

**Comment by maciejwalkowiak** [comment] 2023-03-01 09:18
Closing.

**Closed by maciejwalkowiak** 2023-03-01 09:18 UTC
Labels: component: parameter-store
