### ISSUE TITLE
Number MessageAttribute data type for timestamp is incompatible with older versions of Spring Cloud

### ISSUE THREAD

**Issue by Adita9** [awspring/spring-cloud-aws#931] opened 2023-10-30 10:46 UTC
Hello!

I have the same issue as @angeloarenas  in https://github.com/awspring/spring-cloud-aws/issues/791. My publisher was upgraded to spring-cloud-aws-starter-sns 3.0.2 and my consumer is on spring-cloud-starter-aws-messaging 2.6.6 RELEASE.

Message attribute:
attributeName: timestamp
attributeType: number
attributeValue: 1698230823215

The application throws a StringIndexOutOfBoundsException when it tried to parse the attributeType in line 90 - org.springframework.cloud.aws.messaging.support.converter.NotificationRequestConverter#getNumberValue. (spring-cloud-starter-aws-messaging 2.6.6 RELEASE),

I also tried the RawMessageDelivery - it fails in org.springframework.cloud.aws.messaging.core.QueueMessageUtils#getNumberValue  

Do you know any workarounds?

Thank you

**Comment by maciejwalkowiak** [comment] 2023-10-30 11:30
Closing as a duplicate of #791, but fix coming in https://github.com/awspring/spring-cloud-aws/pull/932

**Closed by maciejwalkowiak** 2023-10-30 11:30 UTC
