### ISSUE TITLE
spring-cloud-aws-parameter-store-config prioritizes default-context parameters over service-specific parameters

### ISSUE THREAD

**Issue by MartinStigen** [awspring/spring-cloud-aws#169] opened 2021-07-27 11:52 UTC
**Type**: Bug

**Component**: Parameter Store

**Describe the bug**
Spring Cloud Version: 2.3.1
In parameter store we have two parameters with names:
1. /config/application/xxx
2. /config/my-service/xxx

In our spring application.properties we have the following configuration:
`spring.application.name=my-service`

When we start the application it is the parameter from (1.) that is set, even though we would expect (2.) to override the default-context's parameter. 
Note: If we change `aws.paramstore.default-context` to something else than _application_ it will use the value from (2.).

From the description of default-context it says:
> Shared by all services that have the Configuration support enabled. Can be overridden with a service- or profile-specific property.

So we would expect (2.) to override (1.), but this is not the case?

**Comment by Lucas3oo** [comment] 2021-10-10 07:53
This is pretty much a showstopper to use AWS parameter store.

**Comment by Lucas3oo** [comment] 2021-10-10 09:46
I have as follows in AWS paramstore:
/config/default/use-db=false
/config/stg24/use-db=true

In application.properties:
aws.paramstore.prefix=/config
aws.paramstore.defaultContext=default
aws.paramstore.enabled=true
spring.config.import=aws-parameterstore:

When stating my app:
-Daws.paramstore.name=stg24 

When I run the app I get use-db=false but I expected the "override" value under to take precedence. /config/stg24/use-db=true

**Comment by ericmillinder** [comment] 2021-10-13 14:37
The ordering of locations returned by AwsParamStorePropertySourceLocator does not appear to follow the ascending precedence ordering expected. This looks like it happened way back in https://github.com/spring-cloud/spring-cloud-aws/commit/582fdc6691ead7904aaed176af2cf85221edacd5. The sources have been moved into AwsParamStorePropertySources since then but still maintain a backwards order of precedence. Just look at AwsParamStorePropertySourceLocatorTest and you will see them testing the ordering and it prefers the default context. Maybe this got overlooked after they moved repos?

**Comment by jmax01** [comment] 2022-01-12 16:45
The fix for this broke property loading via secrets manager.

given 
/secret/application
/secret/application/dev1
/secret/MyApp
/secret/MyApp/dev1

With dev1 profile supplied /secret/application is the one chosen.

Reverting to 2.3.2 resolves the issue.

I will open another issue ASAP.

**Comment by WtfJoke** [comment] 2022-01-13 22:44
> The fix for this broke property loading via secrets manager.
> 
> given /secret/application /secret/application/dev1 /secret/MyApp /secret/MyApp/dev1
> 
> With dev1 profile supplied /secret/application is the one chosen.
> 
> Reverting to 2.3.2 resolves the issue.

I cannot reproduce that (at least not for parameter store, which I tried), see my example repo: https://github.com/WtfJoke/chaoskotlindemo/tree/awsparamterstoreconfig (with 2.3.2 it loads the wrong one).

Will try with a secret

**Comment by ademirsoy** [comment] 2022-01-21 12:10
I've face the exact same problem and reverting to 2.3.2 solved it! 
I think this issue should be re-opened.

**Comment by darrelldraney** [comment] 2022-02-03 19:44
@WtfJoke I just ran into this issue when using version 2.3.3 and adding a dependency on `spring-cloud-starter-bootstrap` as opposed to using the `spring.config.import=aws-parameterstore:` property like you did in your example project. Reverting to 2.3.2 and using `spring-cloud-starter-bootstrap` works as expected.

@jmax01 when you ran into this issue with 2.3.3 were you using `spring-cloud-starter-bootstrap` instead of importing the properties like @WtfJoke does in his example project?

**Comment by maciejwalkowiak** [comment] 2022-02-05 20:25
Indeed, this is still broken when used with `spring-cloud-starter-bootstrap`.

**Closed** 2022-02-05 21:56 UTC
Labels: type: bug, component: parameter-store
