### ISSUE TITLE
Log-warnings: hasAcquiredFullPermits was already true

### ISSUE THREAD

**Issue by Vicinzu** [awspring/spring-cloud-aws#692] opened 2023-02-27 16:28 UTC
**Type**: Bug

**Component**: SQS

**Describe the bug**
Hello together,
we have a small set (10) of microservices using spring-cloud-aws 3.0.0-RC1 in combination with spring boot 3.0.2 and noticed sporadic warnings with following content:
> io.awspring.cloud.sqs.listener.SemaphoreBackPressureHandler: hasAcquiredFullPermits was already true

Beside a custom MessageConverter, we use the default configuration for SQS. Each service is subscribed only to one queue.
It seems that only 2 services are affected, one more often than the other.

After reviewing the corresponding code in spring-cloud-aws it does seem to us that it won't have any impact to the functionality. But we still don't understand the cause.

1. Do you have an idea what could be causing it and how to solve it?
2. If it is not really relevant, why do you log it as a warning and not just as an INFO?

Thank you in advance!

**Comment by tomazfernandes** [comment] 2023-03-06 00:05
Hey @Vicinzu, thanks for bringing this up. This log was actually not supposed to appear, that's why it's set to `WARN`. It doesn't indicate a problem per se, but it's worth investigating.

Would you mind setting the logs for `SemaphoreBackPressureHandler` to `DEBUG` in the affected services? It's a bit verbose but would help the investigation.

Thanks.

**Comment by maciejwalkowiak** [comment] 2023-03-07 13:03
Fixed in https://github.com/awspring/spring-cloud-aws/issues/700

**Comment by tomazfernandes** [comment] 2023-03-07 13:05
Hey @maciejwalkowiak, this is not completed yet, we’ll need to investigate this a little further.

**Comment by Vicinzu** [comment] 2023-03-08 16:32
Hello together,
thanks for your support. We enabled the DEBUG logging for the `SemaphoreBackPressureHandler`. It can take some day before we receive the warnings again. One service produced 164 warnings in 3 days, unfortunately before enabling the debugging.

Could you please reopen the issue? The code change only extended the debug message, but does not change anything else.

**Comment by tomazfernandes** [comment] 2023-03-11 23:42
Thanks @Vicinzu, please let us know if it happens again with the DEBUG logs.

**Comment by Vicinzu** [comment] 2023-03-13 08:17
@tomazfernandes We have one occurrence and i attached a CSV with logs of the class beginning approximately 25 minutes before  and 15 after the warning. hope it will help.
[logs.csv](https://github.com/awspring/spring-cloud-aws/files/10955016/logs.csv)

The class is creating a massive amount of debug messages (>1000 per hour), also for services that are not affected by those warnings. We are going to disable it again.

**Comment by Vicinzu** [comment] 2023-03-14 08:04
@tomazfernandes Before disabling the debug logging we got an even better scenario. The warning was logged 36 times in less than 90 minutes. You can find the new log attached to this mail. There are no other log entries beside these.
[logs_36warnings.csv](https://github.com/awspring/spring-cloud-aws/files/10965637/logs_36warnings.csv)

**Comment by tomazfernandes** [comment] 2023-03-14 22:59
Thanks @Vicinzu for the logs. From a first look it seems there's no problem, nevertheless I'll try to create a test to reproduce this behavior.

Can you share any more details on this app's and queue behavior, such as if it's usually idle / empty (logs would suggest so), and how fast or slow is message processing?

Thanks again.

**Comment by Vicinzu** [comment] 2023-03-17 09:25
Hello @tomazfernandes,
at the time where the 36 warnings have been logged, the service/queue was idle. But i cannot assure that it happens only when the queues are idle. I would say that the processing is fast. Most messages are processes in 1-2 ms, the maximum is under 15 ms.

In the following image you can find some statics of the sqs queue for March 13th (when the 36 warnings occurred):
![statistics_36warnings](https://user-images.githubusercontent.com/4351669/225864798-793fd13f-a7ad-427c-9e7b-5ea57726c816.png)

**Comment by tomazfernandes** [comment] 2023-03-20 23:03
Hello @Vicinzu, thank you for bringing this data.

I've submitted a PR with a fix that should take care of this issue. Once it's merged, do you think it would be possible for you to try the `SNAPSHOT` version with this change and confirm if the issue is fixed?

Thanks

**Comment by tomazfernandes** [comment] 2023-03-23 01:59
> @tomazfernandes lets merge it and release RC2

Sounds good. Maybe I can take a look into https://github.com/awspring/spring-cloud-aws/issues/722 since it's the only bug we have open for SQS before we release? I should have time until Sunday at most.

Let's keep this issue open until we confirm it's gone.

**Comment by Vicinzu** [comment] 2023-03-23 08:18
I think would be easiest for us to Test it with the RC2. But if there is no possibility we can try do deploy a snapshot to our test environments.

**Comment by tomazfernandes** [comment] 2023-03-29 00:42
> I think would be easiest for us to Test it with the RC2. But if there is no possibility we can try do deploy a snapshot to our test environments.

@Vicinzu we’ve released RC2, if you can please give it a try. Thanks.

**Comment by Vicinzu** [comment] 2023-03-31 10:20
We updated initially only one of the services to RC2 to check if everything is fine. Today we updated all others. Will let you know as soon i have a warning and/or i am sure that the problem with the warning is solved. :)

**Comment by Vicinzu** [comment] 2023-04-12 06:37
Hello together,

thank you for your support. I had a look to the logs of multiple environment and since a week we did not have any warnings related to this bug: it seems to be fixed. Feel free to close the issue.

**Comment by maciejwalkowiak** [comment] 2023-04-18 04:05
Closing, if it happens again please let us know.

**Closed by maciejwalkowiak** 2023-04-18 04:05 UTC
Labels: type: bug, component: sqs
