### ISSUE TITLE
SQS send/recieve with @SQSListener fails when spring-boot-devtools is present

### ISSUE THREAD

**Issue by amoffet** [awspring/spring-cloud-aws#952] opened 2023-11-11 01:36 UTC
**Type**: Bug

**Component**:"SQS"

**Describe the bug**
In an ordinary spring boot application, where `SqsTemplate` is used to send `MyMessage ` to a queue, and `@SqsListener` handles the incoming Message:

```
 @SqsListener("myQueue")
  public void handleMyMessage(MyMessage myMessage)
```

the listener will not be invoked and an error will occur.  This happens because 'PayloadArgumentMethodResolver#resolveArgument'

examines the `JavaType` and target method parameter to determine if they are the same.

See 

```
        Class<?> targetClass = this.resolveTargetClass(parameter, message);
        Class<?> payloadClass = payload.getClass();
        if (!ClassUtils.isAssignable(targetClass, payloadClass)) {
```

When spring-boot-devtools is present, the restart class loader is used for one and the app class loader for the other.  So, in spite of the classes appearing to be the same, they have different class loaders and so isAssignable returns false.  Consequently the wrong MessageConverter is used and is unable to resolve the message - resulting in an error.  

If spring-boot-devtools is not present, then the app class loader is used for both and the invocation succeeds.

**Sample**

**Comment by maciejwalkowiak** [comment] 2023-11-13 16:46
Yes we are aware and not sure if we are able to fix it. If you have ideas & time, PRs are welcome.

Closing as a duplicate of #657.

**Closed by maciejwalkowiak** 2023-11-13 16:46 UTC
