### ISSUE TITLE
SnsWebConfiguration depends on webmvc

### ISSUE THREAD

**Issue by willerrgit** [awspring/spring-cloud-aws#57] opened 2021-02-12 14:57 UTC
**Type**: Bug

**Component**:
SNS

**Describe the bug**
v. 2.3.0-RC2
Spring (boot 2.4.2) fails to start with ClassNotFoundException. 
We use webflow and have excluded webmvc from the classpath.

**Sample**
The `SnsWebConfiguration.class` depends on mvc at `SnsAutoconfiguration:85`

If you replaced 
`@ConditionalOnClass(WebMvcConfigurer.class)`
with
`@ConditionalOnClass(name = "org.springframework.web.servlet.config.annotation.WebMvcConfigurer.class")`

people who may not have spring webmvc on the classpath may take advantage of this autoconfiguration too. Thanks.

**Comment by MatejNedic** [comment] 2021-02-12 19:02
Hey @willerrgit ,
I can't reproduce an issue. I used this for testing. 
https://github.com/MatejNedic/webmvc-sns-test

**Comment by eddumelendez** [comment] 2021-03-07 23:56
@willerrgit thanks for the report but we are unable to reproduce it and now there is a test which make sure that everything works properly even if the `spring-mvc` dependency is missing. I will close the issue but feel free to reopen with a sample project.

**Closed by eddumelendez** 2021-03-07 23:56 UTC
Labels: status: waiting-for-feedback, type: bug
