### ISSUE TITLE
SQS deserialization fails with a list of items as payload

### ISSUE THREAD

**Issue by huehnerlady** [awspring/spring-cloud-aws#879] opened 2023-09-06 10:56 UTC
**Type**: Bug

**Component**:
SQS

**Describe the bug**
When you have a List of Items as a payload the deserialization will throw an `MessageConversionException`

```
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `com.example.demo.Item` from Array value (token `JsonToken.START_ARRAY`)
 at [Source: (String)"[{foo=foo, bar=bar}, {foo=foo, bar=null}, {foo=null, bar=bar}]"; line: 1, column: 1]
```

For a single item it works fine

**Sample**
I created a [sample project](https://github.com/huehnerlady/demo-sqs) with 2 endpoints which help showing the problem.

**Comment by tomazfernandes** [comment] 2023-09-08 00:23
Hi @huehnerlady, thanks for bringing this up and for the sample project.

The issue itself is you're using the `send` method, where for sending batches the `sendMany` method should be used instead. It's a little more verbose as you'll need to create `Message` instances for each item, but it should work as expected.

That being said, I can see how the API is not being helpful for this scenario and leading to confusion.

A simple way to not let the issue happen might be throwing an exception if a collection is passed to the `send` method.

Another way might be allowing the `send` method to receive the collection and making the switch internally.

Is this something you'd like to open a PR for?

**Comment by huehnerlady** [comment] 2023-09-08 10:15
@tomazfernandes thank you for the answer. I am a bit confused. If I use sendMany I still have one item per message, so it seems to be similar to `list.each{item -> template.send(queue, item)}`, right? So I still do not have the desired result of one message containing a list of items.

Or did I missunderstand?

**Comment by tomazfernandes** [comment] 2023-10-04 02:31
Hi @huehnerlady, sorry for the delay.

If you want to send a single message that contains a list of items, I think the simplest way would be having a wrapper object to encapsulate the list.

If you use the `sendMany` method and send a list of messages, you will send up to 10 messages in a single request, so it's not the same as iterating on the `send` method.

Makes sense? Thanks.

**Comment by huehnerlady** [comment] 2023-10-11 09:00
We did indeed now use a wrapper object. However I still do not understand, why it is not possible anymore to send a list object in the payload. Maybe this Issue can be treated as a feature request - if it is no bug?

**Comment by tomazfernandes** [comment] 2023-10-12 01:20
> We did indeed now use a wrapper object. However I still do not understand, why it is not possible anymore to send a list object in the payload. Maybe this Issue can be treated as a feature request - if it is no bug?

I'd like to understand better what's the use case for sending multiple items in a single message, rather than sending multiple messages, each with an item.

In my mind, you'd send each item in a separate message - both sending and receiving of messages is batched up to 10 messages per request. That would allow those messages to have their own metadata, be processed in parallel, be monitored individually, etc.

Can you clarify a bit your scenario please?

Thanks.

**Comment by huehnerlady** [comment] 2023-10-16 07:46
Hi,

Our use case is parallelising it further.
We did test different scenarios and one of it was increasing the parallel process of messages vs. sending a batch and then parallelising it, and the second option was far quicker in the processing.

So we have a batch of 25 items per message, which then means our service is processing up to 250 items in parallel, which significantly increased our performance.

For me it now feels odd that we have to wrap a simple list in an object, just to achieve the same speed in our processing.
Hence my feature request to allow lists as a payload object

**Comment by marcuslange** [comment] 2023-11-16 18:10
We send small batch messages as a list as well, and have been debugging through this for over a day. Looks like the root of the issue is that the MappingJackson2MessageConverter is deserializing the Message before it goes through the PayloadMethodArgumentResolver. Inspection in the resolver then fails to call the methods as a SmartMessageConverter with a conversionHint. So the object produced ends up an ImmutableCollections.List<LinkedHashMap<String, Object>>. That is the payload that gets processed a second time when it goes through the resolver and blows up.

Essentially the logic the first time the deserialization is called needs to do the same checks as the Resolver, so it calls the correct fromMessage method or the original message needs to be sent to the resolvers.

**Comment by tomazfernandes** [comment] 2023-11-22 22:29
Thanks for the clarification @huehnerlady, and welcome @marcuslange. I agree this is a valid use case. 

When we have a `List<MyPojo>` in `SqsTemplate` or `@SqsListener` it refers to a batch of `SQS` messages. So you can for example receive 10 or 500 as many SQS messages as you like in a single `List` and work on them in large batches, which is a huge performance booster for many use cases.

So I don't think we'd be able to simply make any adjustments to handle assuming a `List<MyPojo>` as being the payload of the message instead.

I think it should be possible to implement a `MessageSink` that would be able to parse a List<MyPojo> to individual messages that would then be processed in parallel - there would be no need for a `List<MyPojo>` in the listener for this scenario (though we could have it).

If any of you have any different ideas and / or would like to provide a prototype I'd be happy to look at it.

**Comment by huehnerlady** [comment] 2023-11-23 13:26
@tomazfernandes thanks for the response. I just run into this problem, because before you did have the possibility to send a list of Objects in one single message. So I am a bit confused why it did work in an earlier version, but not anymore?

**Comment by tomazfernandes** [comment] 2023-12-31 17:34
Hi @huehnerlady, sorry for the delay. This version of the Spring Cloud AWS SQS is a complete rewrite of the integration, with not much code from the previous version.

In this version, we chose to allow using `List<MyPojo>` to receive a batch of SQS messages instead. So now you can i.e. persist a batch of 500 messages at a time to the database, with many polls being processed in parallel in the background, which delivers massive performance that was not possible in the previous version.

Also, in the previous version there was a limit of 10 messages per queue being processed at a time - now there's no such limitation and you can process as many messages in parallel as your application is capable of handling.

I'm thinking now that this pattern of sending a list of messages, while sure increases performance over sending individual ones, was probably also a way to circumvent the 10 messages at a time limitation. So with this limitation being lifted, maybe there will be fewer use cases for it.

**Comment by huehnerlady** [comment] 2024-01-03 08:21
@tomazfernandes thank you for the clarification, for me that means my issue is resolved as it is explained why the change happened 😃

**Comment by huehnerlady** [comment] 2024-01-04 21:14
@tomazfernandes I got some time to look further into this, but it seems with your described approach I cannot achieve to increase the size of my list above 10.

I tried setting the properties:
`spring.cloud.aws.sqs.listener.simple.max-messages-per-poll`
`spring.cloud.aws.sqs.listener.max-inflight-messages-per-queue`
`spring.cloud.aws.sqs.listener.simple.max-concurrent-messages`

but none of those properties changed anything, the highest number in my list is always 10.

Do I really have to create my own `SqsMessageListenerContainerFactory`? Or am I doing something wrong?

The same problem I have with sending more than 10 messages at a time, I always get the error:
`software.amazon.awssdk.services.sqs.model.TooManyEntriesInBatchRequestException: Maximum number of entries per request are 10. You have sent 25.`

**Comment by tomazfernandes** [comment] 2024-01-05 00:47
@huehnerlady just so I can understand, what exactly are you trying to achieve?

> Do I really have to create my own SqsMessageListenerContainerFactory? Or am I doing something wrong?
You can try setting values in the @SqsListener annotation as well.

> software.amazon.awssdk.services.sqs.model.TooManyEntriesInBatchRequestException: Maximum number of entries per request are 10. You have sent 25.

This is unexpected - the Template should divide messages in batches of 10.

Mind that SQS operates with batches of up to 10 messages. What the framework does is aggregate batches in parallel to pass to the listener for receiving, or divide your larger batch in batches of 10 for sending (which apparently has some issue).

**Comment by huehnerlady** [comment] 2024-01-05 08:01
I use this:

```
List<Message<Object>> messages = requests.collate(NUMBER_OF_MESSAGES_IN_BATCH).collect { MessageBuilder.withPayload(it).build() }
queueMessagingTemplate.sendMany(cacheRequestsQueueName, messages)
```

If NUMBER_OF_MESSAGES_IN_BATCH=10, all works, if NUMBER_OF_MESSAGES_IN_BATCH=25 I get the above error.


With listening to the queue we have the following:
```
@SqsListener(value = '${cache.queue.name}')
  void processCacheRequest(List<Object> requests) {
//do something
}
```

In this case, no matter which of the above properties I use, requests.size()<=10, even if there are 1000+ unacknowledged messages in the queue.
I would like it to be higher, eg. 25. Otherwise we have to keep our wrapper object to provide 25 batches as less makes the processing too slow.

**Comment by huehnerlady** [comment] 2024-01-12 08:07
@tomazfernandes is there ant update for us? Or any further information you need?

**Comment by tomazfernandes** [comment] 2024-01-12 23:55
Hi @huehnerlady, sorry for the delay.

We just had an issue where we walked through receiving many messages at once, can you please take a look? https://github.com/awspring/spring-cloud-aws/issues/1017

Flowing these instructions you should be able to process as many messages concurrently as you desire. We can also look for improvements in the documentation if it's not clear enough how it works.

Regarding this error:
`The same problem I have with sending more than 10 messages at a time, I always get the error:
software.amazon.awssdk.services.sqs.model.TooManyEntriesInBatchRequestException: Maximum number of entries per request are 10. You have sent 25.`

Can you give me more context on when this happens? If you could maybe update your sample project to reproduce the issue it'd help a lot.

Please let me know if that works for you.

**Comment by huehnerlady** [comment] 2024-01-15 19:49
@tomazfernandes I tried the way in the other issue with the following properties:

```
spring:
  cloud:
    aws:
    sqs:
      listener:
        simple:
          max-messages-per-poll: 50
          max-concurrent-messages: 50
          poll-timeout: 10
```

I found those properties in the [documentation](https://docs.awspring.io/spring-cloud-aws/docs/3.1.0/reference/html/appendix.html).
Still I only get 10 messages.

While debugging through the code to get the app to stop the listening container at runtime, I found my mistake for the properties (wrong naming AND wrong indentation)

However the publishing problem still exists.

I now adapted the code and you can see in the [Publisher.kt](https://github.com/huehnerlady/demo-sqs/blob/main/src/main/kotlin/com/example/demo/Publisher.kt#L42) that there is a line where I chunk the messages being 10 messages (working) and one where there is 11 (error)

If you need further help, I will be on holiday for a few weeks, but will answer from mid-february

**Comment by huehnerlady** [comment] 2024-02-08 08:29
@tomazfernandes do you have any updates for me?

**Comment by tomazfernandes** [comment] 2024-02-09 00:24
Hey @huehnerlady.

For publishing, I thought we had the logic for sending more than 10 messages but in fact we don't.

We'd need to partition the message list into batches of 10 messages probably around here: 

https://github.com/awspring/spring-cloud-aws/blob/562b9334821ea99d7eeac886e60dd59ef73451b3/spring-cloud-aws-sqs/src/main/java/io/awspring/cloud/sqs/operations/SqsTemplate.java#L350-L356

In the end this is not too different from partitioning the list in the client code and sending to `SqsTemplate` batches of 10 messages since `SQS` itself does not allow sending more than 10 messages in the same request.

One upside I see from doing in the Template though would be handling the requests in parallel properly on behalf of the user, which is not so simple.

I'll open an issue for this enhancement.

On the listening side, everything good?

Thanks.

**Comment by huehnerlady** [comment] 2024-02-09 08:20
@tomazfernandes thank you for adding the issue, I am curious how it will behave then.

As mentioned [here](https://github.com/awspring/spring-cloud-aws/issues/879#issuecomment-1892698876) I did find the error for the listening and so this works fine, however the missing publishing part means we will keep our wrapper object for now and wait till we can also publish more messages.

Many thanks for all your help and in my eyes this issue is completed and the open task will be continued in #1042

**Comment by tomazfernandes** [comment] 2024-02-15 00:02
Hi @huehnerlady, I also appreciate your patience with the delays.

I think in the end what we found out is that, while the previous version supported adding a `List<POJO>` directly as the payload for a single message, the current implementation took a different approach and now understands a List<POJO> as a list of objects to be sent one in each message.

This new approach IMO is more efficient in that you can leverage SQS batch send and batch receive to send and receive many more messages in a single network call independently of each other, so you get separate receive counts, DLQs, etc.

So I think keeping the wrapper object is a reasonable tradeoff, and now you can send and receive many wrapper objects in the same call (as long as it does not exceed SQS payload limits).

The new open issue would enable us to send many batches of up to 10 messages in parallel, which could contain wrapper objects in the payload if that's better for you, thus increasing the overall send throughput by a good amount compared to the previous version or what we can do OOTB in this one.

For now, you can definitely simply partition your list of messages in batches of 10 and send them using the async method, while waiting on the completion of all the returned futures.

Makes sense to you, or am I missing anything?

Thanks

**Comment by huehnerlady** [comment] 2024-02-15 14:02
@tomazfernandes that is a very good summary, thanks :)

**Comment by tomazfernandes** [comment] 2024-02-15 23:32
I'll open an issue to properly document this behavior change - feel free to open a PR for either issues if you'd like.

I'll close this one, we can reopen if necessary.

Thanks

**Closed by tomazfernandes** 2024-02-15 23:32 UTC

**Comment by codecholeric** [comment] 2024-03-22 13:37
Just FYI: I also fell into that pit at first, because we do custom batching of tiny payloads into single messages quite a bit. The tip to use a wrapper object is fine, but in my case I wasn't able to just adjust all the senders to wrap the arrays. And writing a custom deserializer just for this feels not very convenient.

However, I found one simple workaround for my case that I wanted to share quickly: Simply use an array type instead of any `Collection` type. It's not optimal, because arrays just don't handle as nicely as collections, but since the only logic for us usually was to iterate over the separate payloads there wasn't much difference. Of course this still needs a big fat comment to ensure in half a year there won't be somebody coming by thinking "why are they using ugly array types and not simply `List`" 😉
