### ISSUE TITLE
Application cannot register SSM client

### ISSUE THREAD

**Issue by kschlesselmann** [awspring/spring-cloud-aws#108] opened 2021-03-31 07:21 UTC
**Type**: Bug

**Component**:
Parameter Store

**Describe the bug**
Currently we try to migrate our services to Spring Boot 2.4.4, Spring Cloud 2020.0.2 and Spring Cloud AWS 2.3.
As far as I understand the bootstrap context has been deprecated by Spring Cloud Commons and the new way to include configuration via AWS Parameter Store would be
```
spring:
  config:
    import: "aws-parameterstore:"
```
which we have in `application-aws.yml`.

Now after deployment we currently end up with
```
java.lang.IllegalStateException: Could not register object [com.amazonaws.services.simplesystemsmanagement.AWSSimpleSystemsManagementClient@785a4557] under bean name 'configDataAWSSimpleSystemsManagement': there is already object [com.amazonaws.services.simplesystemsmanagement.AWSSimpleSystemsManagementClient@785a4557] bound
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.registerSingleton(DefaultSingletonBeanRegistry.java:124)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.registerSingleton(DefaultListableBeanFactory.java:1138)
    at io.awspring.cloud.autoconfigure.paramstore.AwsParamStoreConfigDataLocationResolver.lambda$registerAndPromoteBean$1(AwsParamStoreConfigDataLocationResolver.java:106)
    at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
    at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
    at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
    at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131)
    at org.springframework.boot.DefaultBootstrapContext.close(DefaultBootstrapContext.java:133)
    at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:392)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:325)
    at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:144)
    at org.springframework.cloud.stream.binder.DefaultBinderFactory.getBinderInstance(DefaultBinderFactory.java:338)
    at org.springframework.cloud.stream.binder.DefaultBinderFactory.doGetBinder(DefaultBinderFactory.java:221)
    at org.springframework.cloud.stream.binder.DefaultBinderFactory.getBinder(DefaultBinderFactory.java:149)
    at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder.bindFunctionToDestinations(FunctionConfiguration.java:443)
    at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder.afterPropertiesSet(FunctionConfiguration.java:401)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1845)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1782)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:602)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
    at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944)
    at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
    at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:63)
    at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:769)
    at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761)
    at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:326)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1313)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302)
    at my.ApplicationKt.main(Application.kt:48)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.base/java.lang.reflect.Method.invoke(Unknown Source)
    at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
    at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
    at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
    at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
```

Any suggestions what's going on here?

**Comment by MatejNedic** [comment] 2021-03-31 08:15
Hey @kschlesselmann , tnx on opening issue.
By any chance is `spring.config.use-legacy-processing = true` being used? If bootstraping is used please use `aws.paramstore.enabled = false`. I think issue might be in this.

**Comment by kschlesselmann** [comment] 2021-03-31 08:28
Nope, we use default settings and AFAIK we'd have to include `spring-cloud-starter-bootstrap` in order to _enable_ bootstrapping, don't we? At least `spring.application.name` isn't read from `bootstrap.yml` any more.

**Comment by MatejNedic** [comment] 2021-03-31 09:16
You are right I mixed it with something else. You would get diffrent stack trace if legacy was set to true. I will have to investigate further.

**Comment by kschlesselmann** [comment] 2021-03-31 09:39
OK, thanks! If you need further details feel free to ask. I'm afraid I cannot share the code though.

**Comment by kschlesselmann** [comment] 2021-04-01 06:41
@MatejNedic Just FYI: I can still reproduce this issue using Spring Cloud AWS 2.3.1

**Comment by eddumelendez** [comment] 2021-04-01 19:35
@kschlesselmann can you share more details, please? Do you have a custom bean for ssm client? can you share the pom?

**Comment by offshorenhstt** [comment] 2021-04-06 07:38
we are getting same issue with Spring Boot 2.4.3 and AWS spring cloud  2.3.1. Solution is working on local but not working on AWS lambda.

**Comment by kschlesselmann** [comment] 2021-04-06 14:39
@eddumelendez No, we do not create a custom bean for SSM. This is our `build.gradle.kts`:
```
import org.asciidoctor.gradle.AsciidoctorTask
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
import org.springframework.boot.gradle.tasks.bundling.BootJar
import org.springframework.cloud.contract.verifier.config.TestFramework
import org.springframework.cloud.contract.verifier.config.TestMode

plugins {
    kotlin("jvm")
    kotlin("plugin.spring")

    id("org.springframework.boot") version "2.4.4"
    id("io.spring.dependency-management") version "1.0.11.RELEASE"
    id("org.springframework.cloud.contract")

    id("com.gorylenko.gradle-git-properties") version "2.2.2"

    jacoco

    id("org.sonarqube") version "2.8"

    id("com.github.ben-manes.versions") version "0.28.0"

    id("org.asciidoctor.convert") version "2.4.0"

    id("maven-publish")
}

val snippetsDir = file("build/generated-snippets")

group = "xxx"

configure<JavaPluginConvention> {
    sourceCompatibility = JavaVersion.VERSION_11
}

configurations {
    compileOnly {
        extendsFrom(configurations.annotationProcessor.get())
    }
}

tasks.withType<KotlinCompile> {
    kotlinOptions {
        jvmTarget = "11"
        freeCompilerArgs = listOf("-Xjsr305=strict")
    }
}

val jaCoCoTestReport = tasks.withType<JacocoReport> {
    reports {
        xml.isEnabled = true
        csv.isEnabled = false
    }
}

val test = tasks.withType<Test> {
    useJUnitPlatform()

    finalizedBy(jaCoCoTestReport)
}

contracts {
    testFramework.set(TestFramework.JUNIT5)
    testMode.set(TestMode.WEBTESTCLIENT)
    baseClassForTests.set("xxx.ContractBaseClass")
    failOnInProgress.set(false)
}

val asciiDoctor = tasks.withType<AsciidoctorTask> {
    inputs.dir(snippetsDir)

    dependsOn(test)
}

springBoot {
    buildInfo()
}

tasks.withType<BootJar> {
    launchScript()

    dependsOn(asciiDoctor)

    from("${asciiDoctor.first().outputDir}/html5") {
        into("static/docs")
    }
}

fun RepositoryHandler.codeArtifact() = maven {
    url = uri("xxx")
    credentials {
        username = "aws"

        val codeArtifactToken: String by project
        password = codeArtifactToken
    }
}

repositories {
    mavenCentral()

    codeArtifact()
}

dependencyManagement {
    imports {
        mavenBom("org.springframework.cloud:spring-cloud-dependencies:2020.0.2")
        mavenBom("io.awspring.cloud:spring-cloud-aws-dependencies:2.3.1")
    }
}

val togglzVersion = "2.9.3"

dependencies {
    // some internal starters (cannot share)

    implementation("com.fasterxml.jackson.module:jackson-module-kotlin")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    implementation("org.jetbrains.kotlin:kotlin-reflect")
    implementation("io.projectreactor.kotlin:reactor-kotlin-extensions")

    implementation("org.springframework.boot:spring-boot-starter-actuator")
    implementation("org.springframework.boot:spring-boot-starter-cache")
    implementation("org.springframework.boot:spring-boot-starter-webflux")
    implementation("org.springframework.boot:spring-boot-starter-hateoas") {
        exclude(group = "org.springframework.boot", module = "spring-boot-starter-tomcat")
        exclude(group = "org.springframework", module = "spring-webmvc")
    }
    implementation("org.springframework.boot:spring-boot-starter-data-mongodb-reactive")
    implementation("org.springframework.boot:spring-boot-starter-security")
    implementation("org.springframework.boot:spring-boot-starter-oauth2-resource-server")
    implementation("org.springframework.boot:spring-boot-starter-oauth2-client")
    implementation("org.togglz:togglz-amazon-s3:$togglzVersion")
    implementation("org.apache.commons:commons-csv:1.8")

    implementation("io.awspring.cloud:spring-cloud-starter-aws")
    implementation("org.springframework.cloud:spring-cloud-starter-bootstrap")
    implementation("org.springframework.cloud:spring-cloud-stream-binder-kafka")

    implementation("io.projectreactor.addons:reactor-extra")
    implementation("javax.cache:cache-api")
    implementation("io.github.microutils:kotlin-logging:1.7.10")
    implementation("net.logstash.logback:logstash-logback-encoder:6.4")

    annotationProcessor("org.springframework.boot:spring-boot-configuration-processor")

    runtimeOnly("org.ehcache:ehcache")
    runtimeOnly("org.springframework.boot:spring-boot-devtools")
    runtimeOnly("io.micrometer:micrometer-registry-cloudwatch")
    runtimeOnly("io.awspring.cloud:spring-cloud-starter-aws-parameter-store-config")
    runtimeOnly("org.springframework.cloud:spring-cloud-starter-sleuth")
    runtimeOnly("org.togglz:togglz-spring-security:$togglzVersion")
    runtimeOnly("com.github.luben:zstd-jni:1.4.5-4")

    testImplementation("org.springframework.boot:spring-boot-starter-test")

    testImplementation("io.projectreactor:reactor-test")
    testImplementation("org.junit.jupiter:junit-jupiter-api")
    testImplementation("org.junit.jupiter:junit-jupiter-params")
    testImplementation("org.springframework.security:spring-security-test")
    testImplementation("com.nhaarman.mockitokotlin2:mockito-kotlin:2.2.0")
    testImplementation("org.togglz:togglz-testing:$togglzVersion")
    testImplementation("org.testcontainers:localstack:1.12.5")

    testImplementation("org.springframework.cloud:spring-cloud-contract-verifier")
    testImplementation("io.rest-assured:spring-web-test-client")
    testImplementation("org.springframework.cloud:spring-cloud-stream") {
        artifact {
            name = "spring-cloud-stream"
            extension = "jar"
            type ="test-jar"
            classifier = "test-binder"
        }
    }
    testImplementation("org.springframework.cloud:spring-cloud-starter-contract-stub-runner")

    testImplementation("org.springframework.restdocs:spring-restdocs-webtestclient")

    asciidoctor("org.springframework.restdocs:spring-restdocs-asciidoctor")

    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine")
    testRuntimeOnly("de.flapdoodle.embed:de.flapdoodle.embed.mongo")
}

publishing {
    repositories {
        codeArtifact()
    }
}
```

**Comment by eddumelendez** [comment] 2021-04-06 14:44
@kschlesselmann is there any reason to use `implementation("org.springframework.cloud:spring-cloud-starter-bootstrap")`? If you are using `spring.config.import=aws-parameterstore:` already there is no need for that dependency.

**Comment by kschlesselmann** [comment] 2021-04-06 15:11
@eddumelendez We do not use `spring.config.import` because this leads to the current issue. We added this dep to get the service up and running at all. Our goal would be to remove it again and migrate to `spring.config.import`.

**Comment by eddumelendez** [comment] 2021-04-06 15:14
it would be great to have a small example to reproduce the error. I have a basic example using `spring.config.import=aws-parameterstore:` but can not get the same exception

**Comment by kschlesselmann** [comment] 2021-04-06 15:22
@offshorenhstt Can you share your POM as well? Maybe we can find some kind of common demoninator?

**Comment by kschlesselmann** [comment] 2021-04-07 10:15
@eddumelendez Hm … I'm trying to reproduce the issue on my machine … right now without success. Could it be some issue with ECS Fargate and some buggy auto configuration?

@offshorenhstt Where do you deploy your service? ECS Fargate as well?

**Comment by kschlesselmann** [comment] 2021-04-08 13:09
@eddumelendez @MatejNedic Seems that Spring Cloud Stream creates this issue: Have a look at https://github.com/kschlesselmann/aws-ssm-issue-sample – as soon as you add a simple function + stream dependency the application startup fails.

**Comment by MatejNedic** [comment] 2021-04-13 16:02
Thanks @kschlesselmann on sample! Will take a look why error is happening in following days.

**Comment by VijayKumarTiwari** [comment] 2021-05-10 06:54
Hello @MatejNedic / @eddumelendez,
We have the same issue, I was trying to understand it and found that at **line 106** in https://github.com/awspring/spring-cloud-aws/blob/2.3.x/spring-cloud-starter-aws-parameter-store-config/src/main/java/io/awspring/cloud/autoconfigure/paramstore/AwsParamStoreConfigDataLocationResolver.java, there is a **registerSingleton**

event.getApplicationContext().getBeanFactory().registerSingleton("configData" + type.getSimpleName(),
					instance);

This fails when being called the second time, in this case, the spring cloud stream starts as a child context and thus ends loading the environment again leading to attempting registration of the singleton bean twice and exception.

Is there any specific reason for the bean to be a singleton, can it be like other beans i.e. using **registerIfAbsent**.

If I am not wrong when the bootstrap is used this is exactly what happens(I mean skipping bean def) by using @ConditionalOnMissingBean.

Does this help and could we change it from registerSingleton to registerIfAbsent?

Thanks.

**Comment by davidmelia** [comment] 2021-05-27 09:48
@MatejNedic any more movement on this? I imagine this blocks many projects moving to spring cloud aws 2.3.x

**Comment by MatejNedic** [comment] 2021-05-27 09:53
Hey @davidmelia,

I was having some issues and was not able to work on a project. Will take deeper look today since I finally have some time free. From quick looks I had before some refactoring will be needed. Hopefully we will be able to have PR soon.

**Closed** 2021-06-17 10:36 UTC
Labels: status: waiting-for-triage, type: bug
