### ISSUE TITLE
Support ResourcePatternResolver for s3

### ISSUE THREAD

**Issue by fjmacagno** [awspring/spring-cloud-aws#515] opened 2022-09-06 21:34 UTC
**Type**: Feature

**Is your feature request related to a problem? Please describe.**
It would nice if we could use the existing Spring approach to getting resources for each file under a path recursively, 
`ResourcePatternUtils.getResourcePatternResolver(resourceLoader).getResources("s3://bucket/key")`.

**Describe the solution you'd like**
When using the above snippet, instead of returning an empty list of resources, it should return a list of Resources, one for each object in s3 under the given key prefix.

**Describe alternatives you've considered**
I can do this manually, but then I loose the Resource abstraction of Spring.

**Additional context**
It seems like it should be possible to update the resourceloader for the S3Resource, but i haven't found where to make that change yet.

**Comment by maciejwalkowiak** [comment] 2022-09-07 04:26
@fjmacagno is it the same as https://github.com/awspring/spring-cloud-aws/issues/432 ?

**Comment by fjmacagno** [comment] 2022-09-07 15:36
Probably? Im not sure exactly if that is the same thing, i don't understand the resource system well enough to know if that solves this issue.

**Comment by maciejwalkowiak** [comment] 2022-09-08 06:25
Ok, no worries, as far as i understand it is the same thing. Closing as a duplicate of #432. @fjmacagno would you like to contribute it?

**Closed by maciejwalkowiak** 2022-09-08 06:25 UTC

**Comment by fjmacagno** [comment] 2022-09-12 16:21
As much as i would like to i have probably hit my not-technically-work-at-work quota for a little while, alas. I will keep it in mind though.
